image:
  file: .gitpod.dockerfile
ports:
- port: 8001
  onOpen: notify
tasks:
- name: Logs
  command: >
    apachectl start;
    clear;
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log -I /var/log/nginx/access.log -I /var/log/nginx/error.log;
